<h1>Nivell 2</h1>

<h2>Exercici 4</h2>
<h3>Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1". </h3>

In [1]:
import numpy as np
arr4=np.random.randint(9, size=(4, 4))
print(arr4)

[[8 2 0 8]
 [3 5 2 3]
 [1 2 8 5]
 [8 6 6 5]]


Array 2*8

In [2]:
arr4.reshape(2,8)

array([[8, 2, 0, 8, 3, 5, 2, 3],
       [1, 2, 8, 5, 8, 6, 6, 5]])

**Array 2 * 2 * 4**

In [3]:
arr4.reshape(2,2,4)

array([[[8, 2, 0, 8],
        [3, 5, 2, 3]],

       [[1, 2, 8, 5],
        [8, 6, 6, 5]]])

**Array 4 * 4 * 1**

In [4]:
arr4.reshape(4,4,1)

array([[[8],
        [2],
        [0],
        [8]],

       [[3],
        [5],
        [2],
        [3]],

       [[1],
        [2],
        [8],
        [5]],

       [[8],
        [6],
        [6],
        [5]]])

In [5]:
#one "unknown" dimension
arr4.reshape(1,2,-1)

array([[[8, 2, 0, 8, 3, 5, 2, 3],
        [1, 2, 8, 5, 8, 6, 6, 5]]])

<h2>Exercici 5</h2>
<h3>Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors. </h3>

In [6]:
arr5=np.random.randint(10, size=(4, 4))
print(arr5)

[[3 9 0 7]
 [9 7 9 8]
 [5 8 9 3]
 [1 9 0 4]]


In [7]:
num=np.random.randint(4)
row=arr5[num]
print ("row    ",num, " - ",row, "  Sum - ",row.sum())
col=arr5[:,num]
print ("column ",num, " - ",col, "  Sum - ",col.sum())

row     3  -  [1 9 0 4]   Sum -  14
column  3  -  [7 8 3 4]   Sum -  22


<h2>Exercici 6</h2>
<h3>Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre. Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul. </h3>

In [8]:
import numpy.ma as ma
maska=arr5%4
MatMask=ma.masked_array(arr5, maska)
MatMask

masked_array(
  data=[[--, --, 0, --],
        [--, --, --, 8],
        [--, 8, --, --],
        [--, --, 0, 4]],
  mask=[[ True,  True, False,  True],
        [ True,  True,  True, False],
        [ True, False,  True,  True],
        [ True,  True, False, False]],
  fill_value=999999)

<h2>Exercici 7</h2>
<h3>A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant. </h3>

In [9]:
MatMask[~MatMask.mask]

masked_array(data=[0, 8, 8, 0, 4],
             mask=[False, False, False, False, False],
       fill_value=999999)