<h1>Nivell 1</h1>

<h2>Exercici 1</h2>
<h3>Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu. </h3>

In [36]:
import numpy as np
arr = np.array([1, 2, 3, 4, 3,5,6,7,8], dtype='int64')

print("Dimension:", arr.ndim)
print("Shape:", arr.shape)


Dimension: 1
Shape: (9,)


<h2>Exercici 2</h2>
<h3>De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.</h3>

In [14]:
media=arr.mean()
arr=arr-media
arr

array([-3.33333333, -2.33333333, -1.33333333, -0.33333333, -1.33333333,
        0.66666667,  1.66666667,  2.66666667,  3.66666667])

<h2>Exercici 3</h2>
<h3>Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos. </h3>

In [39]:
arr3=np.random.randint(15, size=(5, 5))
print(arr3)
print("The maximum value of the array is ",np.amax(arr3))
print ("Maxima along the first axis is ",np.amax(arr3,axis=0))
print ("Maxima along the second axis is",np.amax(arr3,axis=1))

[[ 3  3  5 13  7]
 [14 10 11 10 12]
 [ 9 13 11  2  8]
 [ 8  8 10 11 12]
 [11  4  0  3  3]]
The maximum value of the array is  14
Maxima along the first axis is  [14 13 11 13 12]
Maxima along the second axis is [13 14 13 12 11]
