<h1>Nivell 1</h1>

<h2>Exercici 1</h2>
<h3>Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.</h3>

In [120]:
import numpy as np

def statistica(a):
    if a.ndim==1:
        print("The array is ",a)
        print ("Minimum is", np.amin(a))
        print ("Maximum is", np.amax(a))
        print ("Media", a.mean())
        print("Median",np.median(a))        
        print ("Standard deviatio", np.std(a))
        print ("Percentile",np.percentile(a, 50))
    else:
        print("Error! ")
a=np.random.randint(100, size=(22))
statistica (a)

The array is  [ 7 73 83  6 13 90 89 28 42 53 76 81  4 29 39 67  1 87  2  1 48  0]
Minimum is 0
Maximum is 90
Media 41.77272727272727
Median 40.5
Standard deviatio 33.4010503620658
Percentile 40.5


<h2>Exercici 2</h2>
<h3>Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.</h3>

In [55]:
import numpy as np
def CreateQuadrat(n):
    arr=np.random.randint(101, size=(n, n))
    return arr
print(CreateQuadrat(12))

[[46 36 34 28 91 60 80 45 91 64  6 26]
 [37 77  0 88 64 52 15  3  2  2 72 90]
 [47 30 26 47 82  7  0 66 55 86  8 91]
 [76 22 84 31 70 88  9 89 66 67 99 13]
 [77 93 42 30 20  4  0 32  7 60  5 42]
 [66 89 51 59 28 62 26 74 59 72 10 75]
 [17 63 60 24 75 31 19 53  9 64 89 67]
 [89 90 85  2 95 37 16 12 93  1 47 52]
 [29 84 22 92 30 50 80 60 96 16 18 53]
 [28 98 26 97 38 53 60 13 92 62  3 18]
 [83  5 18  6 88 37 50 27 25  3 19 18]
 [63 68 33 51 92 73 36 18 23 89 71  4]]


<h2>Exercici 3</h2>
<h3>Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.</h3>

In [68]:
def sumArray(arr):
    sumRow=np.sum(arr,axis=1)
    sumCol=np.sum(arr,axis=0)
    return sumRow,sumCol
arr2=np.random.randint(10, size=(5,3))
print ("Array -")
print(arr2)
r,c=sumArray(arr2)
print("Sum of rows - ",r,". Sum of columns - ",c)

Array -
[[4 7 3]
 [7 6 6]
 [0 9 0]
 [1 4 9]
 [5 7 8]]
Sum of rows -  [14 19  9 14 20] . Sum of columns -  [17 33 26]


<h2>Exercici 4</h2>
<h3>Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.</h3>

In [116]:
import math
import random
def CoefCorr(x,y):
    SumX=x.sum()
    SumY=y.sum()
    SumXY,SumXX,SumYY=0,0,0
    for i in range(0,20):
        SumXY+=x[i]*y[i]
        SumXX+=x[i]*x[i]
        SumYY+=y[i]*y[i]
    R=(20*SumXY-SumX*SumY)/(math.sqrt((20*SumXX-SumX*SumX)*(20*SumYY-SumY*SumY)))
    return R

x=np.random.randint(15, size=(20))
y=np.random.randint(15, size=(20))
y1=np.array([k*random.randint(1,3) for k in x])
print ("Example 1")
print(x)
print(y)
print ("Pearson correlation coefficient -", CoefCorr(x,y))
cc = np.corrcoef(x,y)
print("Applying corrcoef() function for control -", cc[0][1])

print (" \nExample 2")
print(x)
print(y1)
print ("Pearson correlation coefficient -", CoefCorr(x,y1))
cc = np.corrcoef(x,y1)
print("Applying corrcoef() function for control -", cc[0][1])

Example 1
[ 7 12 12  6  7  1  5  4  0 11  8 12 14  3  0  4  7  0 13  3]
[ 1  8  3 14 13  2 12  1  8 11 14  3  7  9 11  7  4  1  9  0]
Pearson correlation coefficient - 0.13667739221964714
Applying corrcoef() function for control - 0.13667739221964714
 
Example 2
[ 7 12 12  6  7  1  5  4  0 11  8 12 14  3  0  4  7  0 13  3]
[21 36 36  6 21  2  5  4  0 11  8 36 14  3  0  4 14  0 26  3]
Pearson correlation coefficient - 0.8175455549803932
Applying corrcoef() function for control - 0.8175455549803933
